// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACheckbox: typeof import('ant-design-vue/es')['Checkbox']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputPassword: typeof import('ant-design-vue/es')['InputPassword']
    DrawingApp: typeof import('./src/components/DrawingApp/index.vue')['default']
    DrinkWater: typeof import('./src/components/DrinkWater/index.vue')['default']
    EventKeycodes: typeof import('./src/components/EventKeycodes/index.vue')['default']
    FormWave: typeof import('./src/components/FormWave/index.vue')['default']
    Home: typeof import('./src/components/Home/index.vue')['default']
    Login: typeof import('./src/components/Login/index.vue')['default']
    RandomChoicePicker: typeof import('./src/components/RandomChoicePicker/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThemeClock: typeof import('./src/components/ThemeClock/index.vue')['default']
  }
}
